enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
arch = "arm64-v8a"
build-mode = "module"
version = "latest"
included-patches = "'Hide player button background' 'Premium heading'"

[YT Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
arch = "arm64-v8a"
build-mode = "module"
version = "latest"
included-patches = "'Enable color match player' 'Enable zen mode' 'Hide player overlay filter' 'Hide voice search button' 'Replace cast button'"

YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "module"
version = "latest"
included-patches = "'Enable slide to seek' 'Remove player controls background'"
